app:
    name: spring-boot-config-cloud-refresh
    list: 1,2,4

db:
    connection: "{url:'jdbc://${db.host}:${db.port}/dbname}', user: 'root', pwd: 'rootpwd'}"
    host: 192.168.0.6
    port: 8080
    
spring:
  cloud:
    config:
      uri:
      - http://localhost:8888

  application:
    name: spring-boot-config
    
management.endpoints.web.exposure.include: refresh